swagger: "2.0"
paths:
  '/users':
    post:
      tags:
        - Users
      summary: Create a new user
      description: Create a new user
      operationId: createUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: user
          in: body
          description: User object
          required: true
          schema:
            $ref: '#/User'
      responses:
        '201':
          description: Successfully created
          schema:
            $ref: '#/User'
        default:
          description: Error
          schema:
            $ref: '#/Error'
  '/users/{id}':
    get:
      tags:
        - Users
      summary: Get a user by ID
      description: Get a user by ID
      operationId: getUserById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of user
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successfully retrieved
          schema:
            $ref: '#/User'
        default:
          description: Error
          schema:
            $ref: '#/Error'
