swagger: "2.0"
paths:
  '/users':
    post:
      tags:
        - Users
      summary: Create a new user
      description: Create a new user
      operationId: createUser
    get:
      tags:
        - Users
      summary: Get all users
      description: Get all users
      operationId: getAllUsers